global:
  pattern: xray

  options:
    useCSV: False
    syncPolicy: Automatic
    installPlanApproval: Automatic

  datacenter:
    cloudProvider: OpenShift
    storageClassName: openshift-storage.noobaa.io
    region: na
    clustername: validated
    domain: labgear.io

  xraylab:
    namespace: "xraylab-1"

    s3:
      # Values for S3 bucket access
      # bucketSource: "provide s3 bucket name where images are stored"
      bucketSource: "https://s3-openshift-storage.apps.validated.labgear.io/"
      # Bucket base name used for image-generator and image-server applications.
      bucketBaseName: "medimg-30c692cb-3372-47c2-890b-55007495fed1"

main:
  clusterGroupName: hub

# Example Configuration
  #datacenter:
  #  cloudProvider: aws
  #  storageClassName: gp2
  #  region: us-east-1
  #  clustername: example-sample
  #  domain: patterns.redhat.com

